name: iOS App Build

on:
  push:
    tags:
      - 'universal-v*'
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: Build profile to use
        options:
          - unsigned

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: >
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Get version from universal package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/universal

      - name: Build iOS app
        working-directory: apps/universal
        run: eas build --profile ${{ inputs.profile || 'unsigned' }} --platform ios --local --output ${{ github.workspace }}/build.tar.gz

      - name: Extract and rename iOS app
        run: |
          mkdir -p extracted
          tar -xzf ${{ github.workspace }}/build.tar.gz -C extracted
          mv extracted/universal.app ${{ github.workspace }}/universal-ios-simulator-${{ steps.package-version.outputs.current-version }}.app

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/universal-ios-simulator-${{ steps.package-version.outputs.current-version }}.app

      - name: Upload APK to Release
        if: startsWith(github.ref, 'refs/tags/universal-v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/universal-ios-simulator-${{ steps.package-version.outputs.current-version }}.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
