name: 'Draft new server release'

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The version you want to release.'
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  draft-new-release:
    name: 'Draft a new release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun environment
        uses: oven-sh/setup-bun@v2

      - name: Change to server directory and run changelogen
        working-directory: ./apps/server
        run: |
          bunx changelogen@latest --bump --${{ inputs.semver }}

      - name: Get version from server package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/server

      - name: Create release branch
        run: git checkout -b release/server-v${{ steps.package-version.outputs.current-version }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Commit manifest files
        id: make-commit
        run: |
          git add apps/server/package.json apps/server/CHANGELOG.md
          git commit --message "Prepare release server-v${{ steps.package-version.outputs.current-version }}"

          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release/server-v${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/server-v${{ steps.package-version.outputs.current-version }}
          base: main
          title: Release version server-v${{ steps.package-version.outputs.current-version }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.

            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.